from dataclasses import dataclass
from enum import IntEnum


class AccelProfile(IntEnum):
  eco = 0
  normal = 1
  sport = 2


@dataclass(frozen=True)
class ProfileConfig:
  comfort_decel: float


PROFILE_CONFIGS = {
  AccelProfile.eco: ProfileConfig(comfort_decel=0.25),
  AccelProfile.normal: ProfileConfig(comfort_decel=0.30),
  AccelProfile.sport: ProfileConfig(comfort_decel=0.35),
}

ACCEL_PROFILE_MAX_BP = [0.0, 3.0, 10.0, 25.0, 40.0]
ACCEL_PROFILE_MAX_V = {
  AccelProfile.eco: [1.65, 1.30, 0.72, 0.32, 0.16],
  AccelProfile.normal: [1.80, 1.50, 0.97, 0.48, 0.30],
  AccelProfile.sport: [2.00, 1.90, 1.15, 0.68, 0.42],
}

CAP_FILTER_FRAMES = 5
LEAD_LOSS_HOLD_TIME = 0.50
PACE_RESTRICT_DEADBAND = 0.15
PACE_RELIEF_DEADBAND = 0.35
PACE_TARGET_ARM_MARGIN = 1.0
PACE_TARGET_RESERVE = 0.10
LAUNCH_TARGET_HEADROOM = 3.0
LAUNCH_TARGET_SLEW = 8.75
LAUNCH_END_SPEED = 3.0
ACCEL_LIMIT_HORIZON_JERK = 1.0
LEAD_MATCH_GAP_GAIN = 0.04
LEAD_MATCH_SPEED_HEADROOM = 1.25
LEAD_MATCH_TAPER_GAIN = 1.00
LEAD_MATCH_ACCEL_SLEW = 0.25
MATCHED_PACE_DECEL_RATE = 0.50
BRAKING_ACCEL_LIMIT_THRESHOLD = -0.11
MPC_DECEL_JERK_COST_MULTIPLIER = 1.05
MPC_DECEL_JERK_MAX_REQUIRED_DECEL = 0.80
MPC_DECEL_JERK_MAX_REQUIRED_DECEL_RATE = 0.35
MPC_DECEL_JERK_MAX_TARGET_REDUCTION = 9.0

STOP_HOLD_EGO_SPEED = 0.30
STOPPED_LEAD_SPEED = 0.30
STOP_HOLD_EXIT_SPEED = 0.80
STOP_HOLD_EXIT_FRAMES = 4
STOP_HOLD_CREEP_SPEED = 0.15
STOP_HOLD_CREEP_DISTANCE = 0.30
STOP_HOLD_FAST_DEPARTURE_DISTANCE = 0.03
STOP_HOLD_MAX_LEAD_DISTANCE = 30.0
STOP_GAP_RESERVE = 0.75
STOP_GAP_RESERVE_LEAD_SPEED = 2.0
STOP_GAP_RESERVE_DECEL_BP = (0.30, 0.80)

RADAR_STALE_TIMEOUT = 0.50
MAX_LEAD_ACCEL_TAU = 10.0
MIN_LEAD_SPEED = -1.0
VEGO_NOISE_TOLERANCE = 0.10
