bGVnZW5kID0gWyJMQVRfQUNDRUxfRkFDVE9SIiwgIk1BWF9MQVRfQUNDRUxf
TUVBU1VSRUQiLCAiRlJJQ1RJT04iXQojIyMgYW5nbGUgY29udHJvbAojIE5p
c3NhbiBhcHBlYXJzIHRvIGhhdmUgdG9ycXVlCiJOSVNTQU5fWFRSQUlMIiA9
IFtuYW4sIDEuNSwgbmFuXQoiTklTU0FOX0FMVElNQSIgPSBbbmFuLCAxLjUs
IG5hbl0KIk5JU1NBTl9MRUFGX0lDIiA9IFtuYW4sIDEuNSwgbmFuXQoiTklT
U0FOX0xFQUYiID0gW25hbiwgMS41LCBuYW5dCiJOSVNTQU5fUk9HVUUiID0g
W25hbiwgMS41LCBuYW5dCgojIFBTQSBhbmdsZSBiYXNlZCBjb250cm9sbGVy
cwoiUFNBX1BFVUdFT1RfMjA4IiA9IFtuYW4sIDIuMCwgbmFuXQoKIyBOZXcg
c3ViYXJ1cyBhbmdsZSBiYXNlZCBjb250cm9sbGVycwoiU1VCQVJVX0ZPUkVT
VEVSXzIwMjIiID0gW25hbiwgMy4wLCBuYW5dCiJTVUJBUlVfT1VUQkFDS18y
MDIzIiA9IFtuYW4sIDMuMCwgbmFuXQoiU1VCQVJVX0FTQ0VOVF8yMDIzIiA9
IFtuYW4sIDMuMCwgbmFuXQoKIyBUb3lvdGEgTFRBIGFsc28gaGFzIHRvcnF1
ZQoiVE9ZT1RBX1JBVjRfVFNTMl8yMDIzIiA9IFtuYW4sIDMuMCwgbmFuXQoK
IyBUZXNsYSBhbmdsZSBiYXNlZCBjb250cm9sbGVycwoiVEVTTEFfTU9ERUxf
MyIgPSBbbmFuLCAyLjUsIG5hbl0KIlRFU0xBX01PREVMX1kiID0gW25hbiwg
Mi41LCBuYW5dCiJURVNMQV9NT0RFTF9YIiA9IFtuYW4sIDIuNSwgbmFuXQoK
IyBHdWVzcwoiVk9MS1NXQUdFTl9JRDRfTUsxIiA9IFtuYW4sIDIuNSwgbmFu
XQoiVk9MS1NXQUdFTl9JRDRfTUsyIiA9IFtuYW4sIDIuNSwgbmFuXQoiQ1VQ
UkFfQk9STl9NSzEiID0gW25hbiwgMi41LCBuYW5dCiJGT1JEX0JST05DT19T
UE9SVF9NSzEiID0gW25hbiwgMS41LCBuYW5dCiJGT1JEX0VTQ0FQRV9NSzQi
ID0gW25hbiwgMS41LCBuYW5dCiJGT1JEX0VTQ0FQRV9NSzRfNSIgPSBbbmFu
LCAxLjUsIG5hbl0KIkZPUkRfRVhQTE9SRVJfTUs2IiA9IFtuYW4sIDEuNSwg
bmFuXQoiRk9SRF9FWFBFRElUSU9OX01LNCIgPSBbbmFuLCAxLjUsIG5hbl0K
IkZPUkRfRl8xNTBfTUsxNCIgPSBbbmFuLCAxLjUsIG5hbl0KIkZPUkRfRk9D
VVNfTUs0IiA9IFtuYW4sIDEuNSwgbmFuXQoiRk9SRF9NQVZFUklDS19NSzEi
ID0gW25hbiwgMS41LCBuYW5dCiJGT1JEX0ZfMTUwX0xJR0hUTklOR19NSzEi
ID0gW25hbiwgMS41LCBuYW5dCiJGT1JEX01VU1RBTkdfTUFDSF9FX01LMSIg
PSBbbmFuLCAxLjUsIG5hbl0KIkZPUkRfUkFOR0VSX01LMiIgPSBbbmFuLCAx
LjUsIG5hbl0KIyMjCgojIE5vIHN0ZWVyaW5nIHdoZWVsCiJDT01NQV9CT0RZ
IiA9IFtuYW4sIDEwMDAsIG5hbl0KCiMgVG90YWxseSBuZXcgY2FycwoiUkFN
XzE1MDBfNVRIX0dFTiIgPSBbMi4wLCAyLjAsIDAuMDVdCiJSQU1fSERfNVRI
X0dFTiIgPSBbMS40LCAxLjQsIDAuMDVdCiJTVUJBUlVfT1VUQkFDSyIgPSBb
Mi4wLCAxLjUsIDAuMl0KIkNBRElMTEFDX0VTQ0FMQURFIiA9IFsxLjg5OTk5
OTk3NjE1ODE0MiwgMS44NDIyNzAwMTY2NzAyMjcsIDAuMTEyMDAwMDAzNDU3
MDY5NF0KIkNBRElMTEFDX0VTQ0FMQURFX0VTVl8yMDE5IiA9IFsxLjE1LCAx
LjMsIDAuMl0KIkNBRElMTEFDX1hUNCIgPSBbMS40NSwgMS42LCAwLjJdCiJD
SEVWUk9MRVRfQk9MVF9FVVYiID0gWzEuMCwgMi4wLCAwLjE3NV0KIkNIRVZS
T0xFVF9TSUxWRVJBRE8iID0gWzEuOSwgMS45LCAwLjExMl0KIkNIRVZST0xF
VF9UUkFJTEJMQVpFUiIgPSBbMS4zMywgMS45LCAwLjE2XQoiQ0hFVlJPTEVU
X1RSQVZFUlNFIiA9IFsxLjMzLCAxLjMzLCAwLjE4XQoiQ0hFVlJPTEVUX0VR
VUlOT1giID0gWzIuNSwgMi41LCAwLjA1XQoiQ0hFVlJPTEVUX1ZPTFRfMjAx
OSIgPSBbMS40LCAxLjQsIDAuMTZdCiJWT0xLU1dBR0VOX0NBRERZX01LMyIg
PSBbMS4yLCAxLjIsIDAuMV0KIlZPTEtTV0FHRU5fUEFTU0FUX05NUyIgPSBb
Mi41LCAyLjUsIDAuMV0KIlZPTEtTV0FHRU5fU0hBUkFOX01LMiIgPSBbMi41
LCAyLjUsIDAuMV0KIkhZVU5EQUlfU0FOVEFfQ1JVWl8xU1RfR0VOIiA9IFsy
LjcsIDIuNywgMC4xXQoiS0lBX1NQT1JUQUdFXzVUSF9HRU4iID0gWzIuNiwg
Mi42LCAwLjFdCiJHRU5FU0lTX0dWNzBfMVNUX0dFTiIgPSBbMi40MiwgMi40
MiwgMC4xXQoiR0VORVNJU19HVjYwX0VWXzFTVF9HRU4iID0gWzIuNSwgMi41
LCAwLjFdCiJHTUNfWVVLT04iID0gWzEuMiwgMi41LCAwLjI2XQoiS0lBX1NP
UkVOVE9fNFRIX0dFTiIgPSBbMi41LCAyLjUsIDAuMV0KIktJQV9TT1JFTlRP
X0hFVl80VEhfR0VOIiA9IFsyLjUsIDIuNSwgMC4xXQoiS0lBX05JUk9fSEVW
XzJORF9HRU4iID0gWzIuNDIsIDIuNSwgMC4xMl0KIktJQV9OSVJPX0VWXzJO
RF9HRU4iID0gWzIuMDUsIDIuNSwgMC4xNF0KIkdFTkVTSVNfR1Y4MCIgPSBb
Mi41LCAyLjUsIDAuMV0KIktJQV9DQVJOSVZBTF80VEhfR0VOIiA9IFsxLjc1
LCAxLjc1LCAwLjE1XQoiR01DX0FDQURJQSIgPSBbMS42LCAxLjYsIDAuMl0K
IkxFWFVTX0lTX1RTUzIiID0gWzIuMCwgMi4wLCAwLjFdCiJIWVVOREFJX0tP
TkFfRVZfMk5EX0dFTiIgPSBbMi41LCAyLjUsIDAuMV0KIkhZVU5EQUlfSU9O
SVFfNiIgPSBbMi41LCAyLjUsIDAuMDA1XQoiSFlVTkRBSV9BWkVSQV82VEhf
R0VOIiA9IFsxLjgsIDEuOCwgMC4xXQoiSFlVTkRBSV9BWkVSQV9IRVZfNlRI
X0dFTiIgPSBbMS44LCAxLjgsIDAuMV0KIktJQV9LOF9IRVZfMVNUX0dFTiIg
PSBbMi41LCAyLjUsIDAuMV0KIkhZVU5EQUlfQ1VTVElOXzFTVF9HRU4iID0g
WzIuNSwgMi41LCAwLjFdCiJMRVhVU19HU19GIiA9IFsyLjUsIDIuNSwgMC4w
OF0KIkhZVU5EQUlfU1RBUklBXzRUSF9HRU4iID0gWzEuOCwgMi4wLCAwLjE1
XQoiR0VORVNJU19HVjcwX0VMRUNUUklGSUVEXzFTVF9HRU4iID0gWzEuOSwg
MS45LCAwLjA5XQoiR0VORVNJU19HODBfMk5EX0dFTl9GTCIgPSBbMi41ODE5
MzU2NDQxNDk3ODAzLCAyLjUsIDAuMTEyNDQ1Njg5NzM3Nzk2NzhdCiMgTm90
ZSB0aGF0IHNvbWUgUml2aWFucyBhY2hpZXZlIHNpZ25pZmljYW50bHkgbGVz
cyBsYXRlcmFsIGFjY2VsZXJhdGlvbiB0aGFuIHRoaXMKIlJJVklBTl9SMSIg
PSBbMi44LCAyLjUsIDAuMDddCiJIWVVOREFJX05FWE9fMVNUX0dFTiIgPSBb
Mi41LCAyLjUsIDAuMV0KIkhPTkRBX0FDQ09SRF8xMUciID0gWzEuMzUsIDEu
MzUsIDAuMTddCiJIT05EQV9QSUxPVF80RyIgPSBbMS4yNSwgMS4yNSwgMC4y
MV0KIkhPTkRBX1BBU1NQT1JUXzRHIiA9IFsxLjIsIDEuMiwgMC4xNl0KIkFD
VVJBX01EWF80R19NTVIiID0gWzEuMjUsIDEuMjUsIDAuMTVdCiJIT05EQV9D
UlZfNkciID0gWzEuMywgMS4zLCAwLjJdCiJIT05EQV9DSVRZXzdHIiA9IFsx
LjIsIDEuMiwgMC4yM10KIkhPTkRBX09EWVNTRVlfNUdfTU1SIiA9IFswLjks
IDAuOSwgMC4yXQoiSE9OREFfTkJPWF8yRyIgPSBbMS4yLCAxLjIsIDAuMl0K
IkFDVVJBX1RMWF8yRyIgPSBbMS4yLCAxLjIsIDAuMTVdCiJBQ1VSQV9UTFhf
MkdfTU1SIiA9IFsxLjcsIDEuNywgMC4xNl0KIlBPUlNDSEVfTUFDQU5fTUsx
IiA9IFsyLjAsIDIuMCwgMC4yXQoiQVVESV9RNV9NSzEiID0gWzEuOCwgMS44
LCAwLjE4XQoiTEVYVVNfTFMiID0gWzEuMzUsIDEuNywgMC4xN10KIlRPWU9U
QV9SQVY0X1BSSU1FIiA9IFsxLjcsIDIuMCwgMC4xNF0KIlRPWU9UQV9SQVY0
X1RTUzJfMjAyMiIgPSBbMS45LCAxLjkzMDQ0MDcyMDgwOTAwMjksIDAuMTEy
MTc0XQoiS0lBX0s3XzIwMTciID0gWzIuMiwgMi4yLCAwLjFdCiJKRUVQX0NI
RVJPS0VFXzVUSF9HRU4iID0gWzEuNSwgMS41LCAwLjE1XQoiQUNVUkFfTURY
XzRHIiA9IFsxLjQsIDEuNCwgMC4xN10KIkFDVVJBX1JEWF8zR19NTVIiID0g
WzEuNSwgMS41LCAwLjE2XQoKIyBEYXNoY2FtIG9yIGZhbGxiYWNrIGNvbmZp
Z3VyZWQgYXMgaWRlYWwgY2FyCiJNT0NLIiA9IFsxMC4wLCAxMCwgMC4wXQoK
IyBNYW51YWxseSBjaGVja2VkCiJIT05EQV9DSVZJQ18yMDIyIiA9IFsyLjUs
IDEuMiwgMC4xNV0KIkhPTkRBX0hSVl8zRyIgPSBbMi41LCAxLjIsIDAuMl0K
CiMgcG9ydCBleHRlbnNpb25zCiJIT05EQV9DTEFSSVRZIiA9IFswLjk2LCAw
LjQwMTg1MTg3NDA4MTkyMjksIDAuMTldCiJDSEVWUk9MRVRfTUFMSUJVX05P
Tl9BQ0NfOVRIX0dFTiIgPSBbMS44NSwgMS44NSwgMC4wNzVdCg==
